### ISSUE TITLE
Everything is black

### ISSUE THREAD

**Issue by electricytart** [Barbelot/Unity-Skybox-Blender#1]
I removed the script and the reflection probe and
![image_2022-06-04_035137919](https://user-images.githubusercontent.com/74485365/171990149-a0efc313-cfd2-4011-a235-c8322dfb92c2.png)
 now everything is black.

**Comment by Barbelot** [comment]
Did you replaced your scene skybox after removing the script and reflection probe ?

**Comment by Mashimaro7** [comment]
> Did you replaced your scene skybox after removing the script and reflection probe ?

Just letting you know, this happened on my project too... I tried baking the lighting, replacing the skybox, replacing the lighting settings, I had no reflection probes, the only fix was to revert my Github repo.

**Comment by dustinmorman** [comment]
After you delete the scripts check the lighting settings. It looks like one of the functions of the script adjusts the lighting setting from skybox to Custom under "Environment Reflections"
Before
![image](https://user-images.githubusercontent.com/45053470/219158091-1aced96b-72ac-4bb6-8ba3-e43ecc70e103.png)
After
![image](https://user-images.githubusercontent.com/45053470/219158261-7f865543-f053-49e9-8cf1-d806369924f2.png)

**Comment by Barbelot** [comment]
Thanks a lot for the update @dustinmorman ! I haven't be using this for years so I'm glad you found the issue.

Indeed the RenderSettings are modified to set the Environment Reflection Source to Custom Reflections at the end of the UpdateReflectionProbe function of the SkyboxBlender script.

I'll add it to the README.
